version: '3'
services:
  neo4j:
    image: neo4j:4.0.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/secret
      - NEO4J_dbms_connectors_default__listen__address0.0.0.0
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\* \
      - NEO4J_dbms_connector_bolt_address=0.0.0.0:7687

volumes:
  neo4j-plugins: